// Huge mappings extracted from the original MMM-MyTeams-LeagueTable.js
// Centralized for cleaner modular architecture (PERF-01)

export const BBC_URL_MAP = {
	ALBANIA_KATEGORIA_SUPERIORE:           "https://www.bbc.co.uk/sport/football/albanian-superliga/table",
	ALGERIA_LIGUE_1:                       "https://www.bbc.co.uk/sport/football/algerian-ligue-one/table",
	ANDORRA_PRIMERA_DIVISION:              "https://www.bbc.co.uk/sport/football/andorran-primera-division/table",
	ARGENTINA_PRIMERA_DIVISION:            "https://www.bbc.co.uk/sport/football/argentine-primera-division/table",
	ARMENIA_PREMIER_LEAGUE:                "https://www.bbc.co.uk/sport/football/armenian-premier-league/table",
	AUSTRALIA_A_LEAGUE:                    "https://www.bbc.co.uk/sport/football/australian-a-league/table",
	AUSTRIA_BUNDESLIGA:                    "https://www.bbc.co.uk/sport/football/austrian-bundesliga/table",
	AZERBAIJAN_PREMIER_LEAGUE:             "https://www.bbc.co.uk/sport/football/azerbaijan-premier-league/table",
	BELARUS_VYSSHAYA_LIGA:                 "https://www.bbc.co.uk/sport/football/belarusian-vysshaya-liga/table",
	BELGIUM_PRO_LEAGUE:                    "https://www.bbc.co.uk/sport/football/belgian-pro-league/table",
	BOLIVIA_LIGA_PRIMERA_DIVISION:         "https://www.bbc.co.uk/sport/football/bolivian-primera-division/table",
	BOSNIA_AND_HERZEGOVINA_PREMIER_LEAGUE: "https://www.bbc.co.uk/sport/football/bosnian-premier-league/table",
	BRAZIL_SERIA_A:                        "https://www.bbc.co.uk/sport/football/brazilian-serie-a/table",
	CANADA_MLS:                            "https://www.bbc.co.uk/sport/football/major-league-soccer/table",
	CHINA_SUPER_LEAGUE:                    "https://www.bbc.co.uk/sport/football/chinese-super-league/table",
	CROATIA_HNL:                           "https://www.bbc.co.uk/sport/football/croatian-first-league/table",
	CYMRU_PREMIER_LEAGUE:                  "https://www.bbc.co.uk/sport/football/cymru-premier/table",
	CYPRUS_FIRST_DIVISION:                 "https://www.bbc.co.uk/sport/football/cypriot-first-division/table",
	CZECH_LIGA:                            "https://www.bbc.co.uk/sport/football/czech-liga/table",
	DENMARK_SUPERLIGA:                     "https://www.bbc.co.uk/sport/football/danish-superliga/table",
	ENGLAND_CHAMPIONSHIP:                  "https://www.bbc.co.uk/sport/football/english-championship/table",
	ENGLAND_PREMIER_LEAGUE:                "https://www.bbc.co.uk/sport/football/premier-league/table",
	ESTONIA_MEISTRILIIGA:                  "https://www.bbc.co.uk/sport/football/estonian-meistriliiga/table",
	FAROE_ISLANDS_PREMIER_LEAGUE:          "https://www.bbc.co.uk/sport/football/faroe-islands-premier-league/table",
	FRANCE_LIGUE1:                         "https://www.bbc.co.uk/sport/football/french-ligue-one/table",
	GEORGIA_EROVNULI_LIGA:                 "https://www.bbc.co.uk/sport/football/georgian-erovnuli-liga/table",
	GERMANY_BUNDESLIGA:                    "https://www.bbc.co.uk/sport/football/german-bundesliga/table",
	GREECE_SUPER_LEAGUE:                   "https://www.bbc.co.uk/sport/football/greek-superleague/table",
	HUNGARY_NBI:                           "https://www.bbc.co.uk/sport/football/hungarian-nb-i/table",
	ICELAND_PREMIER_LEAGUE:                "https://www.bbc.co.uk/sport/football/icelandic-premier-league/table",
	IRELAND_PREMIER_LEAGUE:                "https://www.bbc.co.uk/sport/football/irish-premier-league/table",
	ISRAEL_PREMIER_LEAGUE:                 "https://www.bbc.co.uk/sport/football/israeli-premier-league/table",
	ITALY_SERIE_A:                         "https://www.bbc.co.uk/sport/football/italian-serie-a/table",
	JAPAN_J1_LEAGUE:                       "https://www.bbc.co.uk/sport/football/japanese-j1-league/table",
	KAZAKHSTAN_PREMIER_LEAGUE:             "https://www.bbc.co.uk/sport/football/kazakhstan-premier-league/table",
	LATVIA_VIRSLIGA:                       "https://www.bbc.co.uk/sport/football/latvian-virsliga/table",
	LITHUANIA_A_LYGA:                      "https://www.bbc.co.uk/sport/football/lithuanian-a-lyga/table",
	MEXICO_LIGA_MX:                        "https://www.bbc.co.uk/sport/football/mexican-liga-mx/table",
	MOLDOVA_SUPER_LIGA:                    "https://www.bbc.co.uk/sport/football/moldovan-super-liga/table",
	MONTENEGRO_FIRST_LEAGUE:               "https://www.bbc.co.uk/sport/football/montenegrin-first-league/table",
	MOROCCO_BOTOLA_PRO:                    "https://www.bbc.co.uk/sport/football/moroccan-botola-pro/table",
	NETHERLANDS_EREDIVISIE:                "https://www.bbc.co.uk/sport/football/dutch-eredivisie/table",
	NORTH_MACEDONIA_FIRST_LEAGUE:          "https://www.bbc.co.uk/sport/football/macedonian-first-league/table",
	NORTHERN_IRELAND_PREMIER_LEAGUE:       "https://www.bbc.co.uk/sport/football/northern-ireland-premier-league/table",
	NORWAY_ELITESERIEN:                    "https://www.bbc.co.uk/sport/football/norwegian-tippeligaen/table",
	POLAND_EKSTRAKLASA:                    "https://www.bbc.co.uk/sport/football/polish-ekstraklasa/table",
	PORTUGAL_PRIMEIRA_LIGA:                "https://www.bbc.co.uk/sport/football/portuguese-primeira-liga/table",
	SCOTLAND_CHAMPIONSHIP:                 "https://www.bbc.co.uk/sport/football/scottish-championship/table",
	SCOTLAND_PREMIERSHIP:                  "https://www.bbc.co.uk/sport/football/scottish-premiership/table",
	SERBIA_SUPER_LIGA:                     "https://www.bbc.co.uk/sport/football/serbian-super-lig/table",
	SOUTH_AFRICA_PREMIER_DIVISION:         "https://www.bbc.co.uk/sport/football/south-african-premier-division/table",
	SOUTH_KOREA_K_LEAGUE_1:                "https://www.bbc.co.uk/sport/football/south-korean-k-league-1/table",
	SPAIN_LA_LIGA:                         "https://www.bbc.co.uk/sport/football/spanish-la-liga/table",
	SWEDEN_ALLSVENSKAN:                    "https://www.bbc.co.uk/sport/football/swedish-allsvenskan/table",
	SWITZERLAND_SUPER_LEAGUE:              "https://www.bbc.co.uk/sport/football/swiss-super-league/table",
	TUNISIA_LIGUE_1:                       "https://www.bbc.co.uk/sport/football/tunisian-ligue-one/table",
	TURKEY_SUPER_LIG:                      "https://www.bbc.co.uk/sport/football/turkish-super-lig/table",
	UKRAINE_PREMIER_LEAGUE:                "https://www.bbc.co.uk/sport/football/ukrainian-premier-league/table",
	USA_MLS:                               "https://www.bbc.co.uk/sport/football/major-league-soccer/table",
	UEFA_CHAMPIONS_LEAGUE: {
		table:    "https://www.bbc.co.uk/sport/football/champions-league/table",
		fixtures: "https://www.bbc.co.uk/sport/football/champions-league/scores-fixtures"
	},
	UEFA_EUROPA_CONFERENCE_LEAGUE: {
		table:    "https://www.bbc.co.uk/sport/football/europa-conference-league/table",
		fixtures: "https://www.bbc.co.uk/sport/football/europa-conference-league/scores-fixtures"
	},
	UEFA_EUROPA_LEAGUE: {
		table:    "https://www.bbc.co.uk/sport/football/europa-league/table",
		fixtures: "https://www.bbc.co.uk/sport/football/europa-league/scores-fixtures"
	},
	WORLD_CUP_2026: [
		"https://www.bbc.co.uk/sport/football/world-cup/scores-fixtures/2026-06",
		"https://www.bbc.co.uk/sport/football/world-cup/scores-fixtures/2026-07"
	],
	ECL: {
		table:    "https://www.bbc.co.uk/sport/football/europa-conference-league/table",
		fixtures: "https://www.bbc.co.uk/sport/football/europa-conference-league/scores-fixtures"
	},
	UCL: {
		table:    "https://www.bbc.co.uk/sport/football/champions-league/table",
		fixtures: "https://www.bbc.co.uk/sport/football/champions-league/scores-fixtures"
	},
	UEL: {
		table:    "https://www.bbc.co.uk/sport/football/europa-league/table",
		fixtures: "https://www.bbc.co.uk/sport/football/europa-league/scores-fixtures"
	}
};

export const WIKIPEDIA_URL_MAP = {
	ALBANIA_KATEGORIA_SUPERIORE:           "https://en.wikipedia.org/wiki/2026%E2%80%9327_Kategoria_Superiore",
	ALGERIA_LIGUE_1:                       "https://en.wikipedia.org/wiki/2026%E2%80%9327_Algerian_Ligue_1",
	ANDORRA_PRIMERA_DIVISION:              "https://en.wikipedia.org/wiki/2026%E2%80%9327_Andorran_Premier_League",
	ARGENTINA_PRIMERA_DIVISION:            "https://en.wikipedia.org/wiki/2026%E2%80%9327_Argentine_Primera_Division",
	ARMENIA_PREMIER_LEAGUE:                "https://en.wikipedia.org/wiki/2026%E2%80%9327_Armenian_Premier_League",
	AUSTRALIA_A_LEAGUE:                    "https://en.wikipedia.org/wiki/2026%E2%80%9327_A-League_Men%27s_competition",
	AUSTRIA_BUNDESLIGA:                    "https://en.wikipedia.org/wiki/2026%E2%80%9327_Austrian_Football_Bundesliga",
	AZERBAIJAN_PREMIER_LEAGUE:             "https://en.wikipedia.org/wiki/2026%E2%80%9327_Azerbaijan_Premier_League",
	BELARUS_VYSSHAYA_LIGA:                 "https://en.wikipedia.org/wiki/2026%E2%80%9327_Belarusian_Premier_League",
	BELGIUM_PRO_LEAGUE:                    "https://en.wikipedia.org/wiki/2026%E2%80%9327_Belgian_Pro_League",
	BOLIVIA_LIGA_PRIMERA_DIVISION:         "https://en.wikipedia.org/wiki/2026%E2%80%9327_Bolivian_Primera_Division",
	BOSNIA_AND_HERZEGOVINA_PREMIER_LEAGUE: "https://en.wikipedia.org/wiki/2026%E2%80%9327_Bosnian_Premier_League",
	BRAZIL_SERIA_A:                        "https://en.wikipedia.org/wiki/2026_in_Brazilian_football#Campeonato_Brasileiro_S%C3%A9rie_A",
	CANADA_MLS:                            "https://en.wikipedia.org/wiki/2026_Major_League_Soccer_season",
	CHINA_SUPER_LEAGUE:                    "https://en.wikipedia.org/wiki/2026_Chinese_Super_League",
	CROATIA_HNL:                           "https://en.wikipedia.org/wiki/2026%E2%80%9327_Croatian_Football_League",
	CYMRU_PREMIER_LEAGUE:                  "https://en.wikipedia.org/wiki/2026%E2%80%9327_Cymru_Premier",
	CYPRUS_FIRST_DIVISION:                 "https://en.wikipedia.org/wiki/2026%E2%80%9327_Cypriot_First_Division",
	CZECH_LIGA:                            "https://en.wikipedia.org/wiki/2026%E2%80%9327_Czech_First_League",
	DENMARK_SUPERLIGA:                     "https://en.wikipedia.org/wiki/2026%E2%80%9327_Danish_Superliga",
	ENGLAND_CHAMPIONSHIP:                  "https://en.wikipedia.org/wiki/2026%E2%80%9327_EFL_Championship",
	ENGLAND_PREMIER_LEAGUE:                "https://en.wikipedia.org/wiki/2026%E2%80%9327_Premier_League",
	ESTONIA_MEISTRILIIGA:                  "https://en.wikipedia.org/wiki/2026_Meistriliiga",
	FAROE_ISLANDS_PREMIER_LEAGUE:          "https://en.wikipedia.org/wiki/2026%E2%80%9327_Faroe_Islands_Premier_League",
	FINLAND_VEIKKAUSLIIGA:                 "https://en.wikipedia.org/wiki/2026_Veikkausliiga",
	FRANCE_LIGUE1:                         "https://en.wikipedia.org/wiki/2026%E2%80%9327_Ligue_1",
	GEORGIA_EROVNULI_LIGA:                 "https://en.wikipedia.org/wiki/2026%E2%80%9327_Erovnuli_Liga",
	GERMANY_BUNDESLIGA:                    "https://en.wikipedia.org/wiki/2026%E2%80%9327_Bundesliga",
	GREECE_SUPER_LEAGUE:                   "https://en.wikipedia.org/wiki/2026%E2%80%9327_Super_League_Greece",
	HUNGARY_NBI:                           "https://en.wikipedia.org/wiki/2026%E2%80%9327_Nemzeti_Bajnoks%C3%A1g_I",
	ICELAND_PREMIER_LEAGUE:                "https://en.wikipedia.org/wiki/2026_%C3%9Arvalsdeild_karla",
	IRELAND_PREMIER_LEAGUE:                "https://en.wikipedia.org/wiki/2026_League_of_Ireland_Premier_Division",
	ISRAEL_PREMIER_LEAGUE:                 "https://en.wikipedia.org/wiki/2026%E2%80%9327_Israeli_Premier_League",
	ITALY_SERIE_A:                         "https://en.wikipedia.org/wiki/2026%E2%80%9327_Serie_A",
	JAPAN_J1_LEAGUE:                       "https://en.wikipedia.org/wiki/2026_J1_League",
	KAZAKHSTAN_PREMIER_LEAGUE:             "https://en.wikipedia.org/wiki/2026_Kazakhstan_Premier_League",
	LATVIA_VIRSLIGA:                       "https://en.wikipedia.org/wiki/2026_Virsliga",
	LITHUANIA_A_LYGA:                      "https://en.wikipedia.org/wiki/2026_A_Lyga",
	MEXICO_LIGA_MX:                        "https://en.wikipedia.org/wiki/2026%E2%80%9327_Liga_MX",
	MOLDOVA_SUPER_LIGA:                    "https://en.wikipedia.org/wiki/2026_Moldovan_National_Division",
	MONTENEGRO_FIRST_LEAGUE:               "https://en.wikipedia.org/wiki/2026%E2%80%9327_Montenegrin_First_League",
	MOROCCO_BOTOLA_PRO:                    "https://en.wikipedia.org/wiki/2026%E2%80%9327_Botola_Pro",
	NETHERLANDS_EREDIVISIE:                "https://en.wikipedia.org/wiki/2026%E2%80%9327_Eredivisie",
	NORTH_MACEDONIA_FIRST_LEAGUE:          "https://en.wikipedia.org/wiki/2026%E2%80%9327_Macedonian_First_League",
	NORTHERN_IRELAND_PREMIER_LEAGUE:       "https://en.wikipedia.org/wiki/2026%E2%80%9327_NIFL_Premiership",
	NORWAY_ELITESERIEN:                    "https://en.wikipedia.org/wiki/2027_Eliteserien",
	POLAND_EKSTRAKLASA:                    "https://en.wikipedia.org/wiki/2026%E2%80%9327_Ekstraklasa",
	PORTUGAL_PRIMEIRA_LIGA:                "https://en.wikipedia.org/wiki/2026%E2%80%9327_Primeira_Liga",
	ROMANIA_LIGA_I:                        "https://en.wikipedia.org/wiki/2026%E2%80%9327_Liga_I",
	SCOTLAND_CHAMPIONSHIP:                 "https://en.wikipedia.org/wiki/2026%E2%80%9327_Scottish_Championship",
	SCOTLAND_PREMIERSHIP:                  "https://en.wikipedia.org/wiki/2026%E2%80%9327_Scottish_Premiership",
	SERBIA_SUPER_LIGA:                     "https://en.wikipedia.org/wiki/2026%E2%80%9327_Serbian_SuperLiga",
	SOUTH_AFRICA_PREMIER_DIVISION:         "https://en.wikipedia.org/wiki/2026%E2%80%9327_Premier_Soccer_League",
	SOUTH_KOREA_K_LEAGUE_1:                "https://en.wikipedia.org/wiki/2026_K_League_1",
	SPAIN_LA_LIGA:                         "https://en.wikipedia.org/wiki/2026%E2%80%9327_La_Liga",
	SWEDEN_ALLSVENSKAN:                    "https://en.wikipedia.org/wiki/2027_Allsvenskan",
	SWITZERLAND_SUPER_LEAGUE:              "https://en.wikipedia.org/wiki/2026%E2%80%9327_Swiss_Super_League",
	TUNISIA_LIGUE_1:                       "https://en.wikipedia.org/wiki/2026%E2%80%9327_Tunisian_Ligue_1",
	TURKEY_SUPER_LIG:                      "https://en.wikipedia.org/wiki/2026%E2%80%9327_S%C3%BCper_Lig",
	UKRAINE_PREMIER_LEAGUE:                "https://en.wikipedia.org/wiki/2026%E2%80%9327_Ukrainian_Premier_League",
	USA_MLS:                               "https://en.wikipedia.org/wiki/2026_Major_League_Soccer_season",
	WALES_PREMIER_LEAGUE:                  "https://en.wikipedia.org/wiki/2026%E2%80%9327_Cymru_Premier",
	UEFA_CHAMPIONS_LEAGUE:                 "https://en.wikipedia.org/wiki/2026%E2%80%9327_UEFA_Champions_League",
	UEFA_EUROPA_CONFERENCE_LEAGUE:         "https://en.wikipedia.org/wiki/2026%E2%80%9327_UEFA_Conference_League",
	UEFA_EUROPA_LEAGUE:                    "https://en.wikipedia.org/wiki/2026%E2%80%9327_UEFA_Europa_League",
	WORLD_CUP_2026:                        "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup"
};

export const SOCCERWAY_URL_MAP = {
	AUSTRIA_BUNDESLIGA:                    "https://int.soccerway.com/national/austria/bundesliga/20262027/regular-season/r00000/",
	CYMRU_PREMIER_LEAGUE:                  "https://int.soccerway.com/national/wales/cymru-premier/20262027/regular-season/r00000/",
	ENGLAND_PREMIER_LEAGUE:                "https://int.soccerway.com/national/england/premier-league/20262027/regular-season/r00000/",
	FRANCE_LIGUE1:                         "https://int.soccerway.com/national/france/ligue-1/20262027/regular-season/r00000/",
	GERMANY_BUNDESLIGA:                    "https://int.soccerway.com/national/germany/bundesliga/20262027/regular-season/r00000/",
	GREECE_SUPER_LEAGUE:                   "https://int.soccerway.com/national/greece/super-league/20262027/regular-season/r00000/",
	ITALY_SERIE_A:                         "https://int.soccerway.com/national/italy/serie-a/20262027/regular-season/r00000/",
	NORWAY_ELITESERIEN:                    "https://int.soccerway.com/national/norway/eliteserien/2026/regular-season/r00000/",
	SCOTLAND_PREMIERSHIP:                  "https://int.soccerway.com/national/scotland/premier-league/20262027/regular-season/r00000/",
	SPAIN_LA_LIGA:                         "https://int.soccerway.com/national/spain/primera-division/20262027/regular-season/r00000/"
};

export const GOOGLE_URL_MAP = {
	ALBANIA_KATEGORIA_SUPERIORE:           "https://www.google.com/search?q=Albania+Kategoria+Superiore+table+standings+2026-27",
	ALGERIA_LIGUE_1:                       "https://www.google.com/search?q=Algeria+Ligue+1+table+standings+2026-27",
	ANDORRA_PRIMERA_DIVISION:              "https://www.google.com/search?q=Andorra+Primera+Divisio+table+standings+2026-27",
	ARGENTINA_PRIMERA_DIVISION:            "https://www.google.com/search?q=Argentine+Primera+Division+table+standings+2026-27",
	ARMENIA_PREMIER_LEAGUE:                "https://www.google.com/search?q=Armenian+Premier+League+table+standings+2026-27",
	AUSTRALIA_A_LEAGUE:                    "https://www.google.com/search?q=Australia+A-League+table+standings+2026-27",
	AUSTRIA_BUNDESLIGA:                    "https://www.google.com/search?q=Austrian+Bundesliga+table+standings+2026-27",
	AZERBAIJAN_PREMIER_LEAGUE:             "https://www.google.com/search?q=Azerbaijan+Premier+League+table+standings+2026-27",
	BELARUS_VYSSHAYA_LIGA:                 "https://www.google.com/search?q=Belarus+Vysshaya+Liga+table+standings+2026-27",
	BELGIUM_PRO_LEAGUE:                    "https://www.google.com/search?q=Belgian+Pro+League+table+standings+2026-27",
	BOLIVIA_LIGA_PRIMERA_DIVISION:         "https://www.google.com/search?q=Bolivia+Primera+Division+table+standings+2026-27",
	BOSNIA_AND_HERZEGOVINA_PREMIER_LEAGUE: "https://www.google.com/search?q=Bosnia+Premier+League+table+standings+2026-27",
	BRAZIL_SERIA_A:                        "https://www.google.com/search?q=Brazilian+Serie+A+table+standings+2027",
	CANADA_MLS:                            "https://www.google.com/search?q=MLS+Major+League+Soccer+table+standings+2027",
	CHINA_SUPER_LEAGUE:                    "https://www.google.com/search?q=China+Super+League+table+standings+2027",
	CROATIA_HNL:                           "https://www.google.com/search?q=Croatia+HNL+table+standings+2026-27",
	CYMRU_PREMIER_LEAGUE:                  "https://www.google.com/search?q=Cymru+Premier+League+table+standings+2026-27",
	CYPRUS_FIRST_DIVISION:                 "https://www.google.com/search?q=Cyprus+First+Division+table+standings+2026-27",
	CZECH_LIGA:                            "https://www.google.com/search?q=Czech+First+Liga+table+standings+2026-27",
	DENMARK_SUPERLIGA:                     "https://www.google.com/search?q=Danish+Superliga+table+standings+2026-27",
	ENGLAND_CHAMPIONSHIP:                  "https://www.google.com/search?q=EFL+Championship+table+standings+2026-27",
	ENGLAND_PREMIER_LEAGUE:                "https://www.google.com/search?q=Premier+League+table+standings+2026-27",
	ESTONIA_MEISTRILIIGA:                  "https://www.google.com/search?q=Estonian+Meistriliiga+table+standings+2027",
	FAROE_ISLANDS_PREMIER_LEAGUE:          "https://www.google.com/search?q=Faroe+Islands+Premier+League+table+standings+2026-27",
	FINLAND_VEIKKAUSLIIGA:                 "https://www.google.com/search?q=Finland+Veikkausliiga+table+standings+2027",
	FRANCE_LIGUE1:                         "https://www.google.com/search?q=Ligue+1+table+standings+2026-27",
	GEORGIA_EROVNULI_LIGA:                 "https://www.google.com/search?q=Georgia+Erovnuli+Liga+table+standings+2026-27",
	GERMANY_BUNDESLIGA:                    "https://www.google.com/search?q=Bundesliga+table+standings+2026-27",
	GREECE_SUPER_LEAGUE:                   "https://www.google.com/search?q=Greek+Super+League+table+standings+2026-27",
	HUNGARY_NBI:                           "https://www.google.com/search?q=Hungarian+NB+I+table+standings+2026-27",
	ICELAND_PREMIER_LEAGUE:                "https://www.google.com/search?q=Iceland+Urvalsdeild+table+standings+2027",
	IRELAND_PREMIER_LEAGUE:                "https://www.google.com/search?q=League+of+Ireland+Premier+Division+table+standings+2027",
	ISRAEL_PREMIER_LEAGUE:                 "https://www.google.com/search?q=Israeli+Premier+League+table+standings+2026-27",
	ITALY_SERIE_A:                         "https://www.google.com/search?q=Serie+A+table+standings+2026-27",
	JAPAN_J1_LEAGUE:                       "https://www.google.com/search?q=J1+League+table+standings+2027",
	KAZAKHSTAN_PREMIER_LEAGUE:             "https://www.google.com/search?q=Kazakhstan+Premier+League+table+standings+2027",
	LATVIA_VIRSLIGA:                       "https://www.google.com/search?q=Latvian+Virsliga+table+standings+2027",
	LITHUANIA_A_LYGA:                      "https://www.google.com/search?q=Lithuanian+A+Lyga+table+standings+2027",
	MEXICO_LIGA_MX:                        "https://www.google.com/search?q=Liga+MX+table+standings+2026-27",
	MOLDOVA_SUPER_LIGA:                    "https://www.google.com/search?q=Moldovan+National+Division+table+standings+2027",
	MONTENEGRO_FIRST_LEAGUE:               "https://www.google.com/search?q=Montenegrin+First+League+table+standings+2026-27",
	MOROCCO_BOTOLA_PRO:                    "https://www.google.com/search?q=Morocco+Botola+Pro+table+standings+2026-27",
	NETHERLANDS_EREDIVISIE:                "https://www.google.com/search?q=Eredivisie+table+standings+2026-27",
	NORTH_MACEDONIA_FIRST_LEAGUE:          "https://www.google.com/search?q=North+Macedonia+First+League+table+standings+2026-27",
	NORTHERN_IRELAND_PREMIER_LEAGUE:       "https://www.google.com/search?q=Northern+Ireland+Premiership+table+standings+2026-27",
	NORWAY_ELITESERIEN:                    "https://www.google.com/search?q=Eliteserien+table+standings+2027",
	POLAND_EKSTRAKLASA:                    "https://www.google.com/search?q=Ekstraklasa+table+standings+2026-27",
	PORTUGAL_PRIMEIRA_LIGA:                "https://www.google.com/search?q=Primeira+Liga+table+standings+2026-27",
	ROMANIA_LIGA_I:                        "https://www.google.com/search?q=Romanian+Superliga+table+standings+2026-27",
	SCOTLAND_CHAMPIONSHIP:                 "https://www.google.com/search?q=Scottish+Championship+table+standings+2026-27",
	SCOTLAND_PREMIERSHIP:                  "https://www.google.com/search?q=Scottish+Premiership+table+standings+2026-27",
	SERBIA_SUPER_LIGA:                     "https://www.google.com/search?q=Serbian+SuperLiga+table+standings+2026-27",
	SOUTH_AFRICA_PREMIER_DIVISION:         "https://www.google.com/search?q=South+Africa+Premier+Soccer+League+table+standings+2026-27",
	SOUTH_KOREA_K_LEAGUE_1:                "https://www.google.com/search?q=K+League+1+table+standings+2027",
	SPAIN_LA_LIGA:                         "https://www.google.com/search?q=La+Liga+table+standings+2026-27",
	SWEDEN_ALLSVENSKAN:                    "https://www.google.com/search?q=Allsvenskan+table+standings+2027",
	SWITZERLAND_SUPER_LEAGUE:              "https://www.google.com/search?q=Swiss+Super+League+table+standings+2026-27",
	TUNISIA_LIGUE_1:                       "https://www.google.com/search?q=Tunisian+Ligue+1+table+standings+2026-27",
	TURKEY_SUPER_LIG:                      "https://www.google.com/search?q=Turkish+Super+Lig+table+standings+2026-27",
	UKRAINE_PREMIER_LEAGUE:                "https://www.google.com/search?q=Ukrainian+Premier+League+table+standings+2026-27",
	USA_MLS:                               "https://www.google.com/search?q=MLS+Major+League+Soccer+table+standings+2027",
	WALES_PREMIER_LEAGUE:                  "https://www.google.com/search?q=Cymru+Premier+League+table+standings+2026-27",
	UEFA_CHAMPIONS_LEAGUE:                 "https://www.google.com/search?q=UEFA+Champions+League+group+standings+2026-27",
	UEFA_EUROPA_CONFERENCE_LEAGUE:         "https://www.google.com/search?q=UEFA+Conference+League+standings+2026-27",
	UEFA_EUROPA_LEAGUE:                    "https://www.google.com/search?q=UEFA+Europa+League+standings+2026-27",
	WORLD_CUP_2026:                        "https://www.google.com/search?q=FIFA+World+Cup+2026+group+standings"
};

export const ESPN_URL_MAP = {
	ARGENTINA_PRIMERA_DIVISION:            "https://www.espn.com/soccer/standings/_/league/arg.1",
	AUSTRALIA_A_LEAGUE:                    "https://www.espn.com/soccer/standings/_/league/aus.1",
	AUSTRIA_BUNDESLIGA:                    "https://www.espn.com/soccer/standings/_/league/aut.1",
	BELGIUM_PRO_LEAGUE:                    "https://www.espn.com/soccer/standings/_/league/bel.1",
	BRAZIL_SERIA_A:                        "https://www.espn.com/soccer/standings/_/league/bra.1",
	CANADA_MLS:                            "https://www.espn.com/soccer/standings/_/league/usa.1",
	CROATIA_HNL:                           "https://www.espn.com/soccer/standings/_/league/cro.1",
	CYMRU_PREMIER_LEAGUE:                  "https://www.espn.com/soccer/standings/_/league/wal.1",
	CYPRUS_FIRST_DIVISION:                 "https://www.espn.com/soccer/standings/_/league/cyp.1",
	CZECH_LIGA:                            "https://www.espn.com/soccer/standings/_/league/cze.1",
	DENMARK_SUPERLIGA:                     "https://www.espn.com/soccer/standings/_/league/den.1",
	ENGLAND_CHAMPIONSHIP:                  "https://www.espn.com/soccer/standings/_/league/eng.2",
	ENGLAND_PREMIER_LEAGUE:                "https://www.espn.com/soccer/standings/_/league/eng.1",
	FRANCE_LIGUE1:                         "https://www.espn.com/soccer/standings/_/league/fra.1",
	GERMANY_BUNDESLIGA:                    "https://www.espn.com/soccer/standings/_/league/ger.1",
	GREECE_SUPER_LEAGUE:                   "https://www.espn.com/soccer/standings/_/league/gre.1",
	HUNGARY_NBI:                           "https://www.espn.com/soccer/standings/_/league/hun.1",
	ISRAEL_PREMIER_LEAGUE:                 "https://www.espn.com/soccer/standings/_/league/isr.1",
	ITALY_SERIE_A:                         "https://www.espn.com/soccer/standings/_/league/ita.1",
	JAPAN_J1_LEAGUE:                       "https://www.espn.com/soccer/standings/_/league/jpn.1",
	MEXICO_LIGA_MX:                        "https://www.espn.com/soccer/standings/_/league/mex.1",
	NETHERLANDS_EREDIVISIE:                "https://www.espn.com/soccer/standings/_/league/ned.1",
	NORWAY_ELITESERIEN:                    "https://www.espn.com/soccer/standings/_/league/nor.1",
	POLAND_EKSTRAKLASA:                    "https://www.espn.com/soccer/standings/_/league/pol.1",
	PORTUGAL_PRIMEIRA_LIGA:                "https://www.espn.com/soccer/standings/_/league/por.1",
	ROMANIA_LIGA_I:                        "https://www.espn.com/soccer/standings/_/league/rou.1",
	SCOTLAND_CHAMPIONSHIP:                 "https://www.espn.com/soccer/standings/_/league/sco.2",
	SCOTLAND_PREMIERSHIP:                  "https://www.espn.com/soccer/standings/_/league/sco.1",
	SERBIA_SUPER_LIGA:                     "https://www.espn.com/soccer/standings/_/league/srb.1",
	SOUTH_KOREA_K_LEAGUE_1:                "https://www.espn.com/soccer/standings/_/league/kor.1",
	SPAIN_LA_LIGA:                         "https://www.espn.com/soccer/standings/_/league/esp.1",
	SWEDEN_ALLSVENSKAN:                    "https://www.espn.com/soccer/standings/_/league/swe.1",
	SWITZERLAND_SUPER_LEAGUE:              "https://www.espn.com/soccer/standings/_/league/sui.1",
	TURKEY_SUPER_LIG:                      "https://www.espn.com/soccer/standings/_/league/tur.1",
	UKRAINE_PREMIER_LEAGUE:                "https://www.espn.com/soccer/standings/_/league/ukr.1",
	USA_MLS:                               "https://www.espn.com/soccer/standings/_/league/usa.1",
	UEFA_CHAMPIONS_LEAGUE:                 "https://www.espn.com/soccer/standings/_/league/uefa.champions",
	UEFA_EUROPA_CONFERENCE_LEAGUE:         "https://www.espn.com/soccer/standings/_/league/uefa.europa.conf",
	UEFA_EUROPA_LEAGUE:                    "https://www.espn.com/soccer/standings/_/league/uefa.europa",
	ECL:                                   "https://www.espn.com/soccer/standings/_/league/uefa.europa.conf",
	UCL:                                   "https://www.espn.com/soccer/standings/_/league/uefa.champions",
	UEL:                                   "https://www.espn.com/soccer/standings/_/league/uefa.europa"
};

export const LEAGUE_SPLITS = {
	ROMANIA_LIGA_I: {
		regularSeasonGames: 30,
		championshipSize: 6,
		relegationSize: 10,
		pointsCarryover: "halved",
		showAllGroups: true,
		groups: [
			{ label: "Play-off Group", size: 6, keywords: ["play-off table", "play-off round", "playoff table", "playoff round", "championship round", "championship group", "championship table"] },
			{ label: "Play-out Group", size: 10, keywords: ["play-out table", "play-out round", "relegation round", "relegation group", "relegation table"] }
		],
		championshipKeywords: ["championship round", "championship group", "playoff round", "play-off round", "play-off table", "playoff table"],
		relegationKeywords: ["relegation round", "relegation group", "play-out round", "play-out table"],
		preferGroup: "championship"
	},
	SCOTLAND_PREMIERSHIP: {
		regularSeasonGames: 33,
		championshipSize: 6,
		relegationSize: 6,
		pointsCarryover: "all",
		showAllGroups: true,
		groups: [
			{ label: "Top Six", size: 6, keywords: ["2nd phase championship group", "2nd phase champions group", "championship group", "championship round", "championship table", "top six", "top 6", "upper tier"] },
			{ label: "Bottom Six", size: 6, keywords: ["2nd phase relegation group", "2nd phase relegate", "relegation group", "relegation round", "relegation table", "bottom six", "bottom 6", "lower tier"] }
		],
		championshipKeywords: ["2nd phase championship group", "championship group", "championship round", "championship table", "top six", "top 6", "upper tier"],
		relegationKeywords: ["2nd phase relegation group", "relegation group", "relegation round", "relegation table", "bottom six", "bottom 6", "lower tier"],
		preferGroup: "championship"
	},
	AUSTRIA_BUNDESLIGA: {
		regularSeasonGames: 22,
		championshipSize: 6,
		relegationSize: 6,
		pointsCarryover: "halved",
		showAllGroups: true,
		groups: [
			{ label: "Championship Group", size: 6, keywords: ["meisterrunde", "meister-gruppe", "meistergruppe", "championship round", "championship group", "championship table"] },
			{ label: "Relegation Group", size: 6, keywords: ["relegationsrunde", "relegation group", "relegation round", "qualifikationsgruppe", "bottom group", "relegation table"] }
		],
		championshipKeywords: ["meisterrunde", "meister-gruppe", "meistergruppe", "top group", "meistergruppe table"],
		relegationKeywords: ["relegation round", "relegation group", "qualifikationsgruppe", "bottom group", "qualifikationsgruppe table"],
		preferGroup: "championship"
	},
	BELGIUM_PRO_LEAGUE: {
		regularSeasonGames: 30,
		championshipSize: 6,
		relegationSize: 10,
		pointsCarryover: "halved",
		showAllGroups: true,
		groups: [
			{ label: "Champions' Play-offs", size: 6, keywords: ["champions' play-offs", "champions play-offs", "championship play-offs", "championship playoff", "championship group", "championship round", "top 6", "po1", "play-offs i", "playoffs i"] },
			{ label: "Europa Play-offs", size: 6, keywords: ["europa play-offs", "europe play-offs", "europa playoffs", "po2", "play-offs ii", "playoffs ii", "europa league play-offs", "conference league play-offs"] },
			{ label: "Relegation Play-offs", size: 4, keywords: ["relegation play-offs", "relegation playoff", "relegation group", "bottom 4", "relegation table"] }
		],
		championshipKeywords: ["champions' play-offs", "champions play-offs", "championship play-offs", "championship playoff", "championship round", "top 6", "championship table"],
		relegationKeywords: ["relegation play-offs", "relegation group", "bottom group", "relegation table"],
		preferGroup: "championship"
	},
	SWITZERLAND_SUPER_LEAGUE: {
		regularSeasonGames: 33,
		championshipSize: 6,
		relegationSize: 6,
		pointsCarryover: "all",
		showAllGroups: true,
		groups: [
			{ label: "Championship Group", size: 6, keywords: ["meisterrunde", "championship group", "championship round", "top 6", "championship table"] },
			{ label: "Relegation Group", size: 6, keywords: ["abstiegsrunde", "relegation group", "relegation round", "bottom 6", "relegation table"] }
		],
		championshipKeywords: ["championship group", "meisterrunde", "top 6", "meisterrunde table"],
		relegationKeywords: ["relegation group", "abstiegsrunde", "bottom 6", "abstiegsrunde table"],
		preferGroup: "championship"
	},
	DENMARK_SUPERLIGA: {
		regularSeasonGames: 22,
		championshipSize: 6,
		relegationSize: 6,
		pointsCarryover: "all",
		showAllGroups: true,
		groups: [
			{ label: "Championship Group", size: 6, keywords: ["championship group", "championship round", "top 6", "upper half", "championship table"] },
			{ label: "Relegation Group", size: 6, keywords: ["relegation group", "relegation round", "bottom 6", "lower half", "relegation table"] }
		],
		championshipKeywords: ["championship group", "top 6", "upper half", "championship table"],
		relegationKeywords: ["relegation group", "bottom 6", "lower half", "relegation table"],
		preferGroup: "championship"
	},
	SERBIA_SUPER_LIGA: {
		regularSeasonGames: 30,
		championshipSize: 8,
		relegationSize: 8,
		pointsCarryover: "all",
		showAllGroups: true,
		groups: [
			{ label: "Championship Group", size: 8, keywords: ["championship group", "championship round", "top 8", "first group", "championship table"] },
			{ label: "Relegation Group", size: 8, keywords: ["relegation group", "relegation round", "bottom 8", "second group", "relegation table"] }
		],
		championshipKeywords: ["championship group", "championship playoff", "championship group", "top 6", "championship table"],
		relegationKeywords: ["relegation round", "relegation playoff", "relegation group", "bottom 8", "relegation table"],
		preferGroup: "championship"
	}
};
